language: rust
rust:
	- stable
	- beta
	- nightly
compiler: gcc
env:
	global:
        - CC_X=gcc-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
matrix:
    allow_failures:
        - rust: nightly
