sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
matrix:
    allow_failures:
        - rust: nightly
