sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - CC=/usr/bin/gcc-4.9
  - CXX=/usr/bin/g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
matrix:
    allow_failures:
        - rust: nightly
