language: rust
rust:
    - stable
    - beta
    - nightly
compiler: gcc
env:
    global:
        - CC_X=gcc-4.8
        - CMAKE_CXX_COMPILER=gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
matrix:
    allow_failures:
        - rust: nightly
