sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - CMAKE_C_COMPILER=gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
before-script:
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
matrix:
    allow_failures:
        - rust: nightly
