language: rust
matrix:
    include:
        - env: CC_X=gcc-4.8 CXX_X=g++-4.8
          os: linux
          rust: stable
          addons:
              apt:
                  packages:
                    - gcc-4.8
    allow_failures:
        - rust: nightly
