language: rust
rust:
    - stable
    - beta
    - nightly
env:
    global:
        - CC_X=gcc-4.8
        - CMAKE_C_COMPILER=gcc
        - CMAKE_CXX_COMPILER=g++
addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
matrix:
    allow_failures:
        - rust: nightly
